/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

// build.gradle.kts (root project)
plugins {
    // Add the Gradle Versions Plugin
    id("com.github.ben-manes.versions") version "0.52.0" // Use the latest stable version
}

// Configure settings applicable to all subprojects
subprojects {
    repositories {
        mavenCentral()
    }

    plugins.withType<JavaPlugin> {
        configure<JavaPluginExtension> {
            // Set Java 21 toolchain for compilation and execution
            toolchain {
                languageVersion.set(JavaLanguageVersion.of(21))
            }
        }

        // Common test configuration
        tasks.withType<Test> {
            useJUnitPlatform()
            testLogging {
                events("passed", "skipped", "failed")
            }
        }
    }
}